AWSTemplateFormatVersion: 2010-09-09
Description: >-
  ai-copilot-be
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: get-all-items.js
  getAllMetricsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-all-metrics.getAllMetricsHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 512
      Timeout: 120
      Description: This function gets the metrics of a product within a given timeline and filters.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the ProductMetricsTable
      - DynamoDBCrudPolicy:
          TableName: !Ref ProductMetricsTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          PRODUCT_METRICS_TABLE: !Ref ProductMetricsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
  
  # Simple syntax to create a DynamoDB table with a single attribute primary key, more in
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlesssimpletable

  # DynamoDB table to store item: {id: &lt;ID&gt;, name: &lt;NAME&gt;}
  ProductMetricsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "metricId"
          AttributeType: "N"
        - AttributeName: "product"
          AttributeType: "S"
        - AttributeName: "date"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "metricId"
          KeyType: "HASH"
        - AttributeName: "product"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      GlobalSecondaryIndexes:
        - IndexName: "product_date_ix"
          KeySchema:
          - AttributeName: "product"
            KeyType: "HASH"
          - AttributeName: "date"
            KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
      TableName: "product-metrics"

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
